
// THESE ARE CONSTANTS WHICH HELPS TO KEEP  IN SYNC BETWEEN ACTION AND REDUCER, SO WE HAVE TO IMPORT THIS CONSTANT FILE IN ACTION AND REDUCER
// THESE ARE ALL ACTION TYPES ACCORDING TO THESE ACTION TYPES WE HAVE TO CREATE ACTIONS

// All the required action types
export const LOADING = 'LOADING';
export const SUCCESS = 'SUCCESS';
export const FAIL = 'FAIL';
// console.log('hi4');
export const GET_TOKEN = 'GET_TOKEN';
export const GET_DETAILS = 'GET_DETAILS';
export const SAFTEY_ALERT  = 'SAFTEY_ALERT'

//component sending to GET_STATUS or Action dispatching
export const GET_STATUS = 'GET_STATUS';
export const GET_AMPWAT = 'GET_AMPWAT';
export const GET_CHANGESTATUS = 'GET_CHANGESTATUS';
export const GET_CHANGEFANSPEED = 'GET_CHANGEFANSPEED';
export const GET_RASPBERRYPILOCALIP = 'GET_RASPBERRYPILOCALIP';
export const GET_HARDMANUAL = 'GET_HARDMANUAL';

export const GET_MODESWITCHS = 'GET_MODESWITCHS';

export const GET_AUTOMANUALSTATUS = 'GET_AUTOMANUALSTATUS';
export const SET_AUTOMANUALSTATUS = 'SET_AUTOMANUALSTATUS';
export const GET_AUTOMATIONDASHBOARD = 'GET_AUTOMATIONDASHBOARD';
export const ENABEL_AUTOMATION = 'ENABEL_AUTOMATION';
export const CHANGE_SWITCHNAME = 'CHANGE_SWITCHNAME';
export const GET_PIRSTATUS = 'GET_PIRSTATUS';
export const SET_PIRSTATUS = 'SET_PIRSTATUS';
export const SET_AUTOMANUALTEMP = 'SET_AUTOMANUALTEMP';

export const GET_RECENTSWITCHS = 'GET_RECENTSWITCHS';

export const ADD_USER = 'ADD_USER';
export const SEARCH_USER = 'SEARCH_USER'
export const GET_USER = 'GET_USER';
export const DELETE_USER = 'DELETE_USER';
export const LOCK_USER = 'LOCK_USER';

// new mode implementation
export const GET_G_MODEDELAILS = 'GET_G_MODEDELAILS';
export const GET_G_CHANGEMODE = 'GET_G_CHANGEMODE';
export const GET_G_ADDMODE = 'GET_G_ADDMODE';
export const GET_G_DELETEMODE = 'GET_G_DELETEMODE';






// ! OLD MODE IMPLEMENTATION
export const MODE_DETAILS = 'MODE_DETAILS';
export const SET_MODE = 'SET_MODE';
export const MODE_NAME = 'MODE_NAME';
export const DELETE_MODE = 'DELETE_MODE';
export const MODE_SWITCH_CHANGE = 'MODE_SWITCH_CHANGE';

export const MODE_SCHEDULE = 'MODE_SCHEDULE';
export const MODE_SCHEDULE_CHANGE = 'MODE_SCHEDULE_CHANGE';
export const MODE_SCHEDULE_DELETE = 'MODE_SCHEDULE_DELETE';
export const MODE_SCHEDULE_ADD = 'MODE_SCHEDULE_ADD';
export const MODE_SCHEDULE_SWITCHS = 'MODE_SCHEDULE_SWITCHS';
export const MODE_SCHEDULE_TIME = 'MODE_SCHEDULE_TIME';

export const SCHEDULE_DASHBOARD = 'SCHEDULE_DASHBOARD';
export const SCHEDULE_LOCATION_LIST = 'SCHEDULE_LOCATION_LIST';
export const SCHEDULE_LOCATION_SWITCHS = 'SCHEDULE_LOCATION_SWITCHS';
export const SCHEDULE_LOCATION_TIME = 'SCHEDULE_LOCATION_TIME';
export const SCHEDULE_LOCATION_CHANGE = 'SCHEDULE_LOCATION_CHANGE';
export const SCHEDULE_LOCATION_DELETE = 'SCHEDULE_LOCATION_DELETE';
export const ADD_SCHEDULE_LOCATION = 'ADD_SCHEDULE_LOCATION';
export const MODIFY_SCHEDULE_LOCATION = 'MODIFY_SCHEDULE_LOCATION';

export const PASSWORDCHANGE = 'PASSWORDCHANGE';

export const RASPBER_PI = 'RASPBER_PI';
export const GET_ALLLOCATION = 'GET_ALLLOCATION';
export const GET_API = 'GET_API';

export const GET_SWITCHDETAILS = 'GET_SWITCHDETAILS';
export const GET_SWITCHSTATUS = 'GET_SWITCHSTATUS';

export const SET_SWITCHSTATUS = 'SET_SWITCHSTATUS';

export const GET_PREESET = 'GET_PREESET';
export const SET_PREESET = 'SET_PREESET';
export const UPDATE_SOCKET = 'UPDATE_SOCKET';

export const SCHEDULE_MODE = 'SCHEDULE_MODE';

export const UPDATE_SCHEDULE_LOCATION = 'UPDATE_SCHEDULE_LOCATION';


